site_name: Fod Documentation
theme:
  name: material

nav:
  - Acasă: index.md
  - Aplicația Fod:
      - Introducere: aplicatia/index.md
      - Crearea soluției: aplicatia/solution create.md
      - Creare proiect Frontoffice: aplicatia/creare proiect frontoffice.md
      - Instalare librarii fod: aplicatia/instalare librarii fod.md
      - Utilizarea stilurilor FOD: aplicatia/utilizarea stilurilor fod.md
      - Înregistrarea serviciilor client: aplicatia/inregistrarea serviciilor client.md
  - Configurare Fod:
      - Roluri și context implicite: configurare/roluri implicite.md
      - Configurare roluri implicite: configurare/configurare roluri implicite.md
      - Configurare roluri particularizate: configurare/configurare roluri particularizate.md
      - MPass: configurare/mpass.md
      - Limbile disponibile: configurare/configurare limbilor disponibile.md
  - Componente:
      - Badge: componente/FodBadge.md
      - Button: componente/FodButton.md
      - Button Group: componente/FodButtonGroup.md
      - Icon Button: componente/FodIconButton.md
      - Chips: componente/FodChip.md
      - ChipSet: componente/FodChipSet.md
      - CheckBox2: componente/FodCheckBox2.md
      - DatePicker: componente/FodDatePicker.md
      - Layout: componente/FodLayout.md
      - Footer: componente/FodFooter.md
      - Wizard: componente/FodWizard.md
  - Componente business:
      - Afișarea costului: componente/bussiness/FodRequestCost.md

  - Servicii:
      - ICurrentUserContextService: servicii/ICurrentUserContextService.md
  - Modele:
      - UserContext: modele/UserContext.md
