site_name: Fod Documentation

theme:
    name: material

nav:
    - Acasă: index.md
    - Aplicația Fod:
          - Introducere: aplicatia/index.md
          - Cerinte: aplicatia/cerinte.md
          - Cunostinte: aplicatia/cunostinte.md
          - Crearea soluției: aplicatia/solution create.md
          - Structura soluției: aplicatia/structura solutiei.md
          - Descriere frontoffice: aplicatia/frontoffice.md
          - Creare proiect Frontoffice: aplicatia/creare proiect frontoffice.md
          - Descrierea Frontoffice-ului: aplicatia/frontoffice.md
          
          - Instalare librarii fod: aplicatia/instalare librarii fod.md
          - Utilizarea stilurilor FOD: aplicatia/utilizarea stilurilor fod.md
          - Înregistrarea serviciilor client: aplicatia/inregistrarea serviciilor client.md
          - Ghid de depunere a unei solicitari: aplicatia/ghid-depunere-solicitare.md
          - Depunere solicitare: aplicatia/depunere.md
          - Pasul Detaliile solicitantului: aplicatia/detalii solicitant.md
          - Pasul Detaliile serviciului: aplicatia/detalii serviciu.md
          - Pasul de apostilare: aplicatia/apostilare.md
          - Pasul modului de recepționare: aplicatia/mod receptionare.md
          - Pasul de confirmare a datelor: aplicatia/confirmarea datelor.md
          - Pasul de semnare: aplicatia/semnare.md
          - Pasul de achitare: aplicatia/achitare.md
          - Pasul de finalizare: aplicatia/finalizare.md
          - Pagina de verificare a solicitării: aplicatia/verificare.md
    - Configurare Fod:
          - Roluri și context implicite: configurare/roluri implicite.md
          - Configurare roluri implicite: configurare/configurare roluri implicite.md
          - Configurare roluri particularizate: configurare/configurare roluri particularizate.md
          - MPass: configurare/mpass.md
          - Limbile disponibile: configurare/configurare limbilor disponibile.md
    - Componente:
          - Alert: componente/FodAlert.md
          - Badge: componente/FodBadge.md
          - Button: componente/FodButton.md
          - Button Group: componente/FodButtonGroup.md
          - Card: componente/FodCard.md
          - CardWrapper: componente/FodCardWrapper.md
          - Checkbox: componente/FodCheckbox.md
          - CheckBox2: componente/FodCheckBox2.md
          - Chips: componente/FodChip.md
          - ChipSet: componente/FodChipSet.md
          - Collapse: componente/FodCollapse.md
          - Container: componente/FodContainer.md
          - Custom Input Select: componente/FodCustomInputSelect.md
          - Custom Multiple Group Select: componente/FodCustomMultipleGroupSelect.md
          - DataTable: componente/FodDataTable.md
          - Display: componente/FodDisplay.md
          - Column: componente/FodColumn.md
          - Tr: componente/FodTr.md
          - Td: componente/FodTd.md
          - Th: componente/FodTh.md
          - THeadRow: componente/FodTHeadRow.md
          - TFootRow: componente/FodTFootRow.md
          - TableSortLabel: componente/FodTableSortLabel.md
          - DatePicker: componente/FodDatePicker.md
          - DateRangePicker: componente/FodDateRangePicker.md
          - Drawer: componente/FodDrawer.md
          - Dropdown: componente/FodDropdown.md
          - Exception Days: componente/FodExceptionDays.md
          - Expansion Panels: componente/FodExpansionPanels.md
          - FAQ Viewer: componente/FodFaqViewer.md
          - Footer: componente/FodFooter.md
          - Grid: componente/FodGrid.md
          - Group Select: componente/FodGroupSelect.md
          - Header: componente/FodHeader.md
          - Icon: componente/FodIcon.md
          - Icon Button: componente/FodIconButton.md
          - Image: componente/FodImage.md
          - Input: componente/FodInput.md
          - Input 1: componente/FodInput1.md
          - Input Adornment: componente/FodInputAdornment.md
          - Input Checkbox: componente/FodInputCheckbox.md
          - Input Control: componente/FodInputControl.md
          - Input File: componente/FodInputFile.md
          - Input Filtered Select: componente/FodInputFilteredSelect.md
          - Inline Checkbox: componente/FodInlineCheckbox.md
          - Input Label: componente/FodInputLabel.md
          - Input Nullable Number: componente/FodInputNullableNumber.md
          - Input Number: componente/FODInputNumber.md
          - Language: componente/FodLanguage.md
          - Input Radio: componente/FODInputRadio.md
          - Input Radio Group: componente/FODInputRadioGroup.md
          - Input Select: componente/FODInputSelect.md
          - Input Text: componente/FODInputText.md
          - Input Wrapper: componente/FODInputWrapper.md
          - Layout: componente/FodLayout.md
          - Link: componente/FodLink.md
          - MainContent: componente/FodMainContent.md
          - List: componente/FodList.md
          - List Item: componente/FodListItem.md
          - Loading: componente/FodLoading.md
          - Loading Circular: componente/FodLoadingCircular.md
          - Loading Linear: componente/FodLoadingLinear.md
          - Menu: componente/FodMenu.md
          - MenuItem: componente/FodMenuItem.md
          - Modal: componente/FodModal.md
          - Nav Menu: componente/FodNavMenu.md
          - Nav Group: componente/FodNavGroup.md
          - Nav Link: componente/FodNavLink.md
          - NotificationProvider: componente/FodNotificationProvider.md
          - Number Box: componente/FodNumberBox.md
          - Overlay: componente/FodOverlay.md
          - Page Content Navigation: componente/FodPageContentNavigation.md
          - Pagination: componente/FodPagination.md
          - Paper: componente/FodPaper.md
          - Popover: componente/FodPopover.md
          - Radio: componente/FodRadio.md
          - Range Input: componente/FodRangeInput.md
          - Rating: componente/FodRating.md
          - Recaptcha: componente/FodRecaptcha.md
          - Search Select: componente/FodSearchSelect.md
          - Select: componente/FodSelect.md
          - Select1: componente/FodSelect1.md
          - Spacer: componente/FodSpacer.md
          - Tab Control: componente/FodTabControl.md
          - Table: componente/FODTable.md
          - Text: componente/FodText.md
          - TextArea: componente/FodTextArea.md
          - Textbox: componente/FodTextbox.md
          - TextField: componente/FodTextField.md
          - Toolbar: componente/FodToolbar.md
          - Tooltip: componente/Tooltip.md
          - FodTooltip: componente/FodTooltip.md
          - User Info: componente/FodUserInfo.md
          - ValidateExtras: componente/FodValidateExtras.md
          - Wizard: componente/FodWizard.md
          - WizardStep: componente/FodWizardStep.md
          - WizardSteps: componente/FodWizardSteps.md
          - WizardLoadingCircle: componente/FodWizardLoadingCircle.md
          - Virtualize: componente/FodVirtualize.md
          - Mask: componente/FodMask.md
          - FileViewer: componente/FileViewer.md
          - FileView: componente/FodFileView.md
          - FileList: componente/FileList.md
          - Navigate: componente/FodNavigate.md
          - Login: componente/FODLogin.md
          - LanguageSelector: componente/LanguageSelector.md
          - CultureSelector: componente/CultureSelector.md
          - OutsideHandleContainer: componente/OutsideHandleContainer.md
    - Componente business:
          - Afișarea costului: componente/bussiness/FodRequestCost.md
          - Datele solicitantului: componente/bussiness/FodRequestor.md
          - Person: componente/FodPerson.md
          - Status cerere: componente/business/FodRequestStatus.md
          - Afișarea Datelor solicitantului: componente/bussiness/FodRequestorDisplay.md
          - ApplicationModelLoader: componente/FodApplicationModelLoader.md
          - Apostila: componente/FodApostila.md
          - Apostila Display: componente/FodApostilaDisplay.md
          - Delivery Display: componente/FodDeliveryDisplay.md
          - Service Request Status: componente/FodServiceRequestStatus.md
          - Service Request Status Response: componente/FodServiceRequestStatusResponse.md
          - Service Requests Statistics: componente/FodServiceRequestsStatistics.md
          - Verify Document: componente/FodVerifyDocument.md
          - Verify Document Response: componente/FodVerifyDocumentResponse.md
          - Feedback: componente/FodFeedback.md
          - Feedback Badge: componente/FodFeedbackBadge.md
          - Context Provider: componente/FodContextProvider.md
          - Context Selector: componente/FodContextSelector.md
          - Context Selector Card: componente/FodContextSelectorCard.md
          - Context Cleaner: componente/FodContextCleaner.md
          - Request Options: componente/FodRequestOptions.md
          - Filter: componente/FodFilter.md
          - MPay Invoice Button: componente/MPayInvoiceButton.md
          - On Behalf Of Radio Group: componente/FODInputOnBehalfOfRadioGroup.md
    - Servicii:
          - ICurrentUserContextService: servicii/ICurrentUserContextService.md
          - IRequestService: servicii/IRequestService.md
          - ApostilaComponentService: servicii/ApostilaComponentService.md
          - AttributeHandlerService: servicii/AttributeHandlerService.md
          - AuthenticationService: servicii/AuthenticationService.md
          - BreakpointService: servicii/BreakpointService.md
          - CaptchaCallbackService: servicii/CaptchaCallbackService.md
          - ConfigurationService: servicii/ConfigurationService.md
          - ContextService: servicii/ContextService.md
          - CostCalculatorService: servicii/CostCalculatorService.md
          - CultureService: servicii/CultureService.md
          - DataRequestHandlerService: servicii/DataRequestHandlerService.md
          - ExceptionDaysService: servicii/ExceptionDaysService.md
          - FeedbackComponentService: servicii/FeedbackComponentService.md
          - FileUploadService: servicii/FileUploadService.md
          - FodNotificationService: servicii/FodNotificationService.md
          - FodPopoverService: servicii/FodPopoverService.md
          - JsApiService: servicii/JsApiService.md
          - NameService: servicii/NameService.md
          - PersonComponentService: servicii/PersonComponentService.md
          - PrintingService: servicii/PrintingService.md
          - RecaptchaService: servicii/RecaptchaService.md
          - RequestStatusService: servicii/RequestStatusService.md
          - RequestorComponentService: servicii/RequestorComponentService.md
          - ResizeBasedService: servicii/ResizeBasedService.md
          - ScrollManager: servicii/ScrollManager.md
          - SelectableItemsService: servicii/SelectableItemsService.md
          - ServiceRequestStatusService: servicii/ServiceRequestStatusService.md
          - ServiceRequestStatisticsService: servicii/ServiceRequestStatisticsService.md
          - SingleFileUploadService: servicii/SingleFileUploadService.md
          - UserService: servicii/UserService.md
          - ValidateExtrasService: servicii/ValidateExtrasService.md
          - VerifyDocumentService: servicii/VerifyDocumentService.md
          - KeyInterceptor: servicii/KeyInterceptor.md
          - OrderNumberGenerator: servicii/OrderNumberGenerator.md
          - EstimatedDateCalculator: servicii/EstimatedDateCalculator.md
          - WorkingProgramService: servicii/WorkingProgramService.md
          - HashGenerator: servicii/HashGenerator.md
          - XmlGenerator: servicii/XmlGenerator.md
          - FaqService: servicii/FaqService.md
          - ApplicationModelLoader: servicii/ApplicationModelLoader.md
    - Modele:
          - UserContext: modele/UserContext.md
          - FodRequestorModel: modele/IRequestor.md
    - Database Entities:
          - BaseEntity: database/entities/BaseEntity.md
          - ExceptionWorkingProgram: database/entities/ExceptionWorkingProgram.md
          - File: database/entities/File.md
          - FileContent: database/entities/FileContent.md
          - FodAdditionalData: database/entities/FodAdditionalData.md
          - FodAdditionalDataTypeValue: database/entities/FodAdditionalDataTypeValue.md
          - FodAdditionalInvoice: database/entities/FodAdditionalInvoice.md
          - FodAdditionalRequest: database/entities/FodAdditionalRequest.md
          - FodAdditionalServiceRequest: database/entities/FodAdditionalServiceRequest.md
          - FodApostilationDetails: database/entities/FodApostilationDetails.md
          - FodDocumentType: database/entities/FodDocumentType.md
          - FodExecutionTerm: database/entities/FodExecutionTerm.md
          - FodMDocsDocumentShare: database/entities/FodMDocsDocumentShare.md
          - FodNotificationType: database/entities/FodNotificationType.md
          - FodPickupLocation: database/entities/FodPickupLocation.md
          - FodPictures: database/entities/FodPictures.md
          - FodRequest: database/entities/FodRequest.md
          - FodRequestDelivery: database/entities/FodRequestDelivery.md
          - FodRequestDeliveryStatusLog: database/entities/FodRequestDeliveryStatusLog.md
          - FodRequestFile: database/entities/FodRequestFile.md
          - FodRequestJson: database/entities/FodRequestJson.md
          - FodRequestJsonSignature: database/entities/FodRequestJsonSignature.md
          - FodRequestPayment: database/entities/FodRequestPayment.md
          - FodRequestType: database/entities/FodRequestType.md
          - FodRequestTypeService: database/entities/FodRequestTypeService.md
          - FodRequestorStatute: database/entities/FodRequestorStatute.md
          - FodResponseDataMDocsDocument: database/entities/FodResponseDataMDocsDocument.md
          - FodResponseDocument: database/entities/FodResponseDocument.md
          - FodResponseJson: database/entities/FodResponseJson.md
          - FodResponseJsonSignature: database/entities/FodResponseJsonSignature.md
          - FodService: database/entities/FodService.md
          - FodServiceAdditionalData: database/entities/FodServiceAdditionalData.md
          - FodServiceDocumentType: database/entities/FodServiceDocumentType.md
          - FodServiceProvider: database/entities/FodServiceProvider.md
          - FodServiceRequest: database/entities/FodServiceRequest.md
          - FodServiceRequestAdditionalData: database/entities/FodServiceRequestAdditionalData.md
          - FodServiceRequestFile: database/entities/FodServiceRequestFile.md
          - FodServiceRequestResponseData: database/entities/FodServiceRequestResponseData.md
          - FodSignature: database/entities/FodSignature.md
          - FodTermsAndCondition: database/entities/FodTermsAndCondition.md
          - FodUserProfileOrganization: database/entities/FodUserProfileOrganization.md
          - FodUserProfileRole: database/entities/FodUserProfileRole.md
          - FodUserSignature: database/entities/FodUserSignature.md
          - JsonSchema: database/entities/JsonSchema.md
          - RSSPAExecutionTerm: database/entities/RSSPAExecutionTerm.md
          - ServiceRequestDelivery: database/entities/ServiceRequestDelivery.md
          - ServiceRequestDeliveryStatusLog: database/entities/ServiceRequestDeliveryStatusLog.md
          - ServiceRequestDiscount: database/entities/ServiceRequestDiscount.md
          - SignableDocument: database/entities/SignableDocument.md
          - UserProfile: database/entities/UserProfile.md
          - WorkingProgram: database/entities/WorkingProgram.md
 