site_name: Fod Documentation
theme:
  name: material

nav:
  - Acasă: index.md
  - Aplicația Fod:
      - Introducere: aplicatia/index.md
      - Crearea soluției: aplicatia/solution create.md
      - Creare proiect Frontoffice: aplicatia/creare proiect frontoffice.md
      - Instalare librarii fod: aplicatia/instalare librarii fod.md
      - Utilizarea stilurilor FOD: aplicatia/utilizarea stilurilor fod.md
      - Înregistrarea serviciilor client: aplicatia/inregistrarea serviciilor client.md
  - Configurare Fod:
      - Prezentare generală: configurare/index.md
  - Componente:
      - Prezentare generală: componente/index.md
  - Servicii:
      - ICurrentUserContextService: servicii/ICurrentUserContextService.md
  - Modele:
      - Prezentare generală: modele/index.md
